language: python
python:
  - "3.6"
# command to install dependencies
cache: pip3
install:
  - 'pip install pandas'
  - 'pip install numpy'
  - 'pip install matplotlib'
  - 'pip install git+https://github.com/UBC-MDS/Pythia.git@master'
  - 'pip install -U pytest'  
# command to run tests
script:
  - cd pythia/tests && pytest
